### ISSUE TITLE
error compiling

### ISSUE THREAD

**Issue by avatar789** [Rochet2/elunamodule#1]
When compiling gives the following errors

e/azerothcore/modules/elunamodule/src/LuaEngine.h:10:20: fatal error: Common.h: No such file or directory
 #include "Common.h"
                    ^
compilation terminated.
make[2]: *** [modules/elunamodule/src/CMakeFiles/eluna.dir/LuaEngine.cpp.o] Error 1
make[1]: *** [modules/elunamodule/src/CMakeFiles/eluna.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

OS Ubuntu

**Comment by Rochet2** [comment]
This is not complete / released
