### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ArthasCore** [Rochet2/elunamodule#2]
In file included from /home/game-server/source/ArthasCore/modules/elunamodule/src/HookHelpers.h:10:0,
                 from /home/game-server/source/ArthasCore/modules/elunamodule/src/CreatureHooks.cpp:8:
/home/game-server/source/ArthasCore/modules/elunamodule/src/LuaEngine.h:10:20: fatal error: Common.h: Нет такого файла или каталога
 #include "Common.h"
                    ^
compilation terminated.
modules/elunamodule/src/CMakeFiles/eluna.dir/build.make:54: ошибка выполнения рецепта для цели «modules/elunamodule/src/CMakeFiles/eluna.dir/CreatureHooks.cpp.o»
make[2]: *** [modules/elunamodule/src/CMakeFiles/eluna.dir/CreatureHooks.cpp.o] Ошибка 1
CMakeFiles/Makefile2:883: ошибка выполнения рецепта для цели «modules/elunamodule/src/CMakeFiles/eluna.dir/all»
make[1]: *** [modules/elunamodule/src/CMakeFiles/eluna.dir/all] Ошибка 2
make[1]: *** Ожидание завершения заданий…

**Comment by Rochet2** [comment]
This is not ready or functional. Not meant to be used.
